# permissions for end users to view netscalerobservabilityexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: netscalerobservabilityexporter-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netscaler-operator
    app.kubernetes.io/part-of: netscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: netscalerobservabilityexporter-viewer-role
rules:
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters/status
  verbs:
  - get
