apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cic-operator
  template:
    metadata:
      labels:
        name: cic-operator
    spec:
      serviceAccountName: cic-operator
      containers:
        - name: cic-operator
          # Replace this with the built image name
          image: registry.connect.redhat.com/citrix/citrix-k8s-ingress-controller:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cic-operator"
            - name: RELATED_IMAGE_CIC
              value: registry.connect.redhat.com/citrix/citrix-ingress-controller:latest
            - name: RELATED_IMAGE_EXPORTER
              value: registry.connect.redhat.com/citrix/citrix-adc-metrics-exporter:latest
